spring.application.name=app-dependency-discovery-api
spring.datasource.url=jdbc:mysql://localhost:3306/unified_portal
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
github.token=
github.apiUrl=https://api.github.com
github.username=anilannamalair
github.repo_owner=anilannamalair
github.workflow_url=https://api.github.com/repos/{anilannamalair}/{custom-workflow}/actions/workflows/clone-and-push.yml/dispatches

github.targetRepo=custom-workflow-destination
github.workflowFile=clone-and-push.yml
gitLab.token=
server.port=8080
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

